### ISSUE TITLE
Persistent IT failures preventing merging PRs

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/java-speech#254] opened 2020-08-11 19:14 UTC
Persistent IT failures need to be fixed:

https://source.cloud.google.com/results/invocations/5ebef2db-b878-402f-90c9-168bd4083498/targets

Blocking #233

**Comment by athakor** [comment] 2020-08-18 13:26
@stephaniewang526 I can't reproduced it, Looks like tests are passing correctly in my local machine. 
and one more thing #233 already unblocked.

closing this issue as it's no longer persist, feel free to reopen if this issue is still persist.

**Closed by athakor** 2020-08-18 13:26 UTC
Labels: api: speech, priority: p1, type: bug
